#!/usr/bin/env bash
# scripts/check-ratchet.sh — shell/generic stack ratchet (generated by 4wd init).
#
# Three metrics:
#   "shellcheck_warnings" — issues across any *.sh files at the repo root tree
#   "test_count"          — bats `@test ` lines OR any "test" file count
#   "todo_count"          — TODO/FIXME comments across the tree
#
# Edit the measurement helpers below — this is a starter. If your project
# tracks different metrics (lint warnings from a custom linter, etc.), wire
# them in here.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BASELINE_FILE="$REPO_ROOT/.ratchet.json"
MODE="${1:-check}"

# ── Measurement ────────────────────────────────────────────────

measure_sc() {
  if ! command -v shellcheck >/dev/null 2>&1; then
    echo "WARN shellcheck not on PATH — skipping shellcheck_warnings" >&2
    echo "ERR"; return
  fi
  local files count
  files=$(find "$REPO_ROOT" -path "$REPO_ROOT/.git" -prune -o -type f -name '*.sh' -print 2>/dev/null || true)
  if [ -z "$files" ]; then echo 0; return; fi
  # shellcheck disable=SC2086
  count=$(shellcheck -f gcc $files 2>&1 | grep -cE ': (note|warning|error):' || true)
  echo "${count:-0}"
}

measure_tests() {
  if [ ! -d "$REPO_ROOT/test" ] && [ ! -d "$REPO_ROOT/tests" ]; then
    echo 0; return
  fi
  local count
  count=$(find "$REPO_ROOT/test" "$REPO_ROOT/tests" -name '*.bats' -type f \
    -exec grep -hcE '^@test ' {} + 2>/dev/null \
    | awk '{s+=$1} END {print s+0}')
  echo "${count:-0}"
}

measure_todos() {
  local count
  count=$(grep -RhcE '\b(TODO|FIXME|XXX)\b' \
    "$REPO_ROOT" --include='*.sh' --include='*.md' --exclude-dir=.git \
    2>/dev/null | awk '{s+=$1} END {print s+0}')
  echo "${count:-0}"
}

# ── Baseline I/O ───────────────────────────────────────────────

read_baseline() {
  if [ ! -f "$BASELINE_FILE" ]; then
    echo "ERROR baseline file not found: $BASELINE_FILE" >&2
    exit 2
  fi
  jq -r "$1 // empty" "$BASELINE_FILE"
}

write_baseline() {
  local sc tests todos
  sc=$(measure_sc); tests=$(measure_tests); todos=$(measure_todos)
  for v in sc tests todos; do
    if [ "${!v}" = "ERR" ]; then
      echo "ERROR cannot lock — measurement for $v crashed" >&2; exit 2
    fi
  done
  cat > "$BASELINE_FILE" <<EOF
{
  "shellcheck_warnings": $sc,
  "test_count": $tests,
  "todo_count": $todos,
  "_note": "Locked $(date -u +%Y-%m-%dT%H:%M:%SZ) on $(uname -s). Run on CI for the canonical baseline."
}
EOF
  echo "Baseline locked → shellcheck=$sc tests=$tests todos=$todos"
}

# ── Dispatch ───────────────────────────────────────────────────

case "$MODE" in
  init)
    [ -f "$BASELINE_FILE" ] && { echo "ERROR $BASELINE_FILE exists. Use 'lock' to overwrite." >&2; exit 2; }
    write_baseline
    ;;
  lock)
    write_baseline
    ;;
  check|"")
    sc=$(measure_sc); tests=$(measure_tests); todos=$(measure_todos)
    base_sc=$(read_baseline .shellcheck_warnings)
    base_tests=$(read_baseline .test_count)
    base_todos=$(read_baseline .todo_count)
    fail=0; win=0

    check_one() {
      local name="$1" cur="$2" base="$3" direction="$4"
      if [ "$cur" = "ERR" ]; then echo "  ⚠️  $name: measurement crashed — skipped"; return; fi
      if [ -z "$base" ] || [ "$base" = "null" ]; then
        echo "  ❓ $name: $cur (no baseline — run \`bash scripts/check-ratchet.sh lock\`)"; return
      fi
      case "$direction" in
        up_bad)
          if [ "$cur" -gt "$base" ]; then echo "  ❌ $name: $cur (+$((cur - base)) over baseline $base)"; fail=1
          elif [ "$cur" -lt "$base" ]; then echo "  ✨ $name: $cur (-$((base - cur)) under baseline $base — lock it!)"; win=1
          else echo "  ✅ $name: $cur (== baseline)"; fi ;;
        down_bad)
          if [ "$cur" -lt "$base" ]; then echo "  ❌ $name: $cur ($((base - cur)) under baseline $base)"; fail=1
          elif [ "$cur" -gt "$base" ]; then echo "  ✨ $name: $cur (+$((cur - base)) over baseline $base — lock it!)"; win=1
          else echo "  ✅ $name: $cur (== baseline)"; fi ;;
      esac
    }

    echo "Ratchet check:"
    check_one "shellcheck_warnings" "$sc"    "$base_sc"    "up_bad"
    check_one "test_count"          "$tests" "$base_tests" "down_bad"
    check_one "todo_count"          "$todos" "$base_todos" "up_bad"
    [ "$win" = 1 ] && { echo; echo "Some metrics improved — lock the win:"; echo "  bash scripts/check-ratchet.sh lock"; }
    exit "$fail"
    ;;
  *)
    echo "Usage: $0 [check|init|lock]" >&2; exit 2
    ;;
esac
