#!/usr/bin/env bash
# scripts/check-ratchet.sh — Python stack ratchet (generated by cma init).
#
# Three metrics:
#   "mypy_errors"  — `mypy --strict` error count (skipped if mypy not installed)
#   "test_count"   — `pytest --collect-only -q` test count
#   "todo_count"   — TODO/FIXME comments across src/ + tests/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BASELINE_FILE="$REPO_ROOT/.ratchet.json"
MODE="${1:-check}"

# ── Measurement ────────────────────────────────────────────────

measure_mypy() {
  if ! command -v mypy >/dev/null 2>&1; then
    echo "WARN mypy not on PATH — skipping mypy_errors metric" >&2
    echo "ERR"; return
  fi
  local out rc count
  out=$(mktemp)
  set +e
  ( cd "$REPO_ROOT" && mypy --strict --no-error-summary . ) >"$out" 2>&1
  rc=$?
  set -e
  if [ "$rc" -ge 128 ]; then
    echo "WARN mypy crashed with exit $rc — skipping mypy_errors metric" >&2
    rm -f "$out"; echo "ERR"; return
  fi
  count=$(grep -cE ': error:' "$out" || true)
  rm -f "$out"
  echo "${count:-0}"
}

measure_tests() {
  if ! command -v pytest >/dev/null 2>&1; then
    echo "WARN pytest not on PATH — skipping test_count metric" >&2
    echo "ERR"; return
  fi
  local out rc count
  out=$(mktemp)
  set +e
  ( cd "$REPO_ROOT" && pytest --collect-only -q --no-header ) >"$out" 2>&1
  rc=$?
  set -e
  if [ "$rc" -ge 128 ]; then
    echo "WARN pytest crashed with exit $rc — skipping test_count metric" >&2
    rm -f "$out"; echo "ERR"; return
  fi
  # pytest emits "N tests collected" or "N/M tests collected" on stdout
  count=$(grep -oE '[0-9]+ tests? collected' "$out" | head -1 | grep -oE '^[0-9]+')
  rm -f "$out"
  echo "${count:-0}"
}

measure_todos() {
  local count
  count=$(grep -RhcE '\b(TODO|FIXME|XXX)\b' \
    "$REPO_ROOT/src" "$REPO_ROOT/tests" "$REPO_ROOT/app" \
    2>/dev/null | awk '{s+=$1} END {print s+0}')
  echo "${count:-0}"
}

# ── Baseline I/O ───────────────────────────────────────────────

read_baseline() {
  if [ ! -f "$BASELINE_FILE" ]; then
    echo "ERROR baseline file not found: $BASELINE_FILE" >&2
    exit 2
  fi
  jq -r "$1 // empty" "$BASELINE_FILE"
}

write_baseline() {
  local mypy tests todos
  mypy=$(measure_mypy); tests=$(measure_tests); todos=$(measure_todos)
  for v in mypy tests todos; do
    if [ "${!v}" = "ERR" ]; then
      echo "ERROR cannot lock — measurement for $v crashed" >&2; exit 2
    fi
  done
  cat > "$BASELINE_FILE" <<EOF
{
  "mypy_errors": $mypy,
  "test_count": $tests,
  "todo_count": $todos,
  "_note": "Locked $(date -u +%Y-%m-%dT%H:%M:%SZ) on $(uname -s). Run on CI for the canonical baseline."
}
EOF
  echo "Baseline locked → mypy=$mypy tests=$tests todos=$todos"
}

# ── Dispatch ───────────────────────────────────────────────────

case "$MODE" in
  init)
    [ -f "$BASELINE_FILE" ] && { echo "ERROR $BASELINE_FILE exists. Use 'lock' to overwrite." >&2; exit 2; }
    write_baseline
    ;;
  lock)
    write_baseline
    ;;
  check|"")
    mypy=$(measure_mypy); tests=$(measure_tests); todos=$(measure_todos)
    base_mypy=$(read_baseline .mypy_errors)
    base_tests=$(read_baseline .test_count)
    base_todos=$(read_baseline .todo_count)
    fail=0; win=0

    check_one() {
      local name="$1" cur="$2" base="$3" direction="$4"
      if [ "$cur" = "ERR" ]; then echo "  ⚠️  $name: measurement crashed — skipped"; return; fi
      if [ -z "$base" ] || [ "$base" = "null" ]; then
        echo "  ❓ $name: $cur (no baseline — run \`bash scripts/check-ratchet.sh lock\`)"; return
      fi
      case "$direction" in
        up_bad)
          if [ "$cur" -gt "$base" ]; then echo "  ❌ $name: $cur (+$((cur - base)) over baseline $base)"; fail=1
          elif [ "$cur" -lt "$base" ]; then echo "  ✨ $name: $cur (-$((base - cur)) under baseline $base — lock it!)"; win=1
          else echo "  ✅ $name: $cur (== baseline)"; fi ;;
        down_bad)
          if [ "$cur" -lt "$base" ]; then echo "  ❌ $name: $cur ($((base - cur)) under baseline $base)"; fail=1
          elif [ "$cur" -gt "$base" ]; then echo "  ✨ $name: $cur (+$((cur - base)) over baseline $base — lock it!)"; win=1
          else echo "  ✅ $name: $cur (== baseline)"; fi ;;
      esac
    }

    echo "Ratchet check:"
    check_one "mypy_errors"  "$mypy"  "$base_mypy"  "up_bad"
    check_one "test_count"   "$tests" "$base_tests" "down_bad"
    check_one "todo_count"   "$todos" "$base_todos" "up_bad"
    [ "$win" = 1 ] && { echo; echo "Some metrics improved — lock the win:"; echo "  bash scripts/check-ratchet.sh lock"; }
    exit "$fail"
    ;;
  *)
    echo "Usage: $0 [check|init|lock]" >&2; exit 2
    ;;
esac
