#!/usr/bin/env bash
# scripts/check-ratchet.sh — Node/TypeScript stack ratchet (generated by 4wd init).
#
# Three metrics:
#   "tsc_errors"   — `tsc --noEmit` error count (skipped if no tsconfig.json)
#   "test_count"   — `it(`, `test(` invocations across src/ + test/ + __tests__/
#   "todo_count"   — TODO/FIXME comments across src/ + test/
#
# Metrics named consistently across stacks so the 4wd dashboard can aggregate.
# Edit the measurement helpers below if your project's layout differs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BASELINE_FILE="$REPO_ROOT/.ratchet.json"
MODE="${1:-check}"

# ── Measurement ────────────────────────────────────────────────

measure_tsc() {
  if [ ! -f "$REPO_ROOT/tsconfig.json" ]; then
    echo "WARN no tsconfig.json — skipping tsc_errors metric" >&2
    echo "ERR"; return
  fi
  if ! command -v npx >/dev/null 2>&1; then
    echo "WARN npx not on PATH — skipping tsc_errors metric" >&2
    echo "ERR"; return
  fi
  local out rc count
  out=$(mktemp)
  set +e
  ( cd "$REPO_ROOT" && npx --no-install tsc --noEmit ) >"$out" 2>&1
  rc=$?
  set -e
  if [ "$rc" -ge 128 ]; then
    echo "WARN tsc crashed with exit $rc — skipping tsc_errors metric" >&2
    rm -f "$out"; echo "ERR"; return
  fi
  count=$(grep -cE "error TS[0-9]+:" "$out" || true)
  rm -f "$out"
  echo "${count:-0}"
}

measure_tests() {
  local count
  # Counts top-level it(/test( calls. Imperfect (skipped tests still count)
  # but stable: rewards adding tests, surfaces deletions.
  count=$(grep -rhcE '^\s*(it|test)\s*\(' \
    "$REPO_ROOT/src" "$REPO_ROOT/test" "$REPO_ROOT/tests" "$REPO_ROOT/__tests__" \
    2>/dev/null | awk '{s+=$1} END {print s+0}')
  echo "${count:-0}"
}

measure_todos() {
  local count
  count=$(grep -RhcE '\b(TODO|FIXME|XXX)\b' \
    "$REPO_ROOT/src" "$REPO_ROOT/test" "$REPO_ROOT/tests" "$REPO_ROOT/__tests__" \
    2>/dev/null | awk '{s+=$1} END {print s+0}')
  echo "${count:-0}"
}

# ── Baseline I/O ───────────────────────────────────────────────

read_baseline() {
  if [ ! -f "$BASELINE_FILE" ]; then
    echo "ERROR baseline file not found: $BASELINE_FILE" >&2
    exit 2
  fi
  jq -r "$1 // empty" "$BASELINE_FILE"
}

write_baseline() {
  local tsc tests todos
  tsc=$(measure_tsc); tests=$(measure_tests); todos=$(measure_todos)
  for v in tsc tests todos; do
    if [ "${!v}" = "ERR" ]; then
      echo "ERROR cannot lock — measurement for $v crashed" >&2; exit 2
    fi
  done
  cat > "$BASELINE_FILE" <<EOF
{
  "tsc_errors": $tsc,
  "test_count": $tests,
  "todo_count": $todos,
  "_note": "Locked $(date -u +%Y-%m-%dT%H:%M:%SZ) on $(uname -s). Run on CI for the canonical baseline."
}
EOF
  echo "Baseline locked → tsc=$tsc tests=$tests todos=$todos"
}

# ── Dispatch ───────────────────────────────────────────────────

case "$MODE" in
  init)
    [ -f "$BASELINE_FILE" ] && { echo "ERROR $BASELINE_FILE exists. Use 'lock' to overwrite." >&2; exit 2; }
    write_baseline
    ;;
  lock)
    write_baseline
    ;;
  check|"")
    tsc=$(measure_tsc); tests=$(measure_tests); todos=$(measure_todos)
    base_tsc=$(read_baseline .tsc_errors)
    base_tests=$(read_baseline .test_count)
    base_todos=$(read_baseline .todo_count)
    fail=0; win=0

    check_one() {
      local name="$1" cur="$2" base="$3" direction="$4"
      if [ "$cur" = "ERR" ]; then echo "  ⚠️  $name: measurement crashed — skipped"; return; fi
      if [ -z "$base" ] || [ "$base" = "null" ]; then
        echo "  ❓ $name: $cur (no baseline — run \`bash scripts/check-ratchet.sh lock\`)"; return
      fi
      case "$direction" in
        up_bad)
          if [ "$cur" -gt "$base" ]; then echo "  ❌ $name: $cur (+$((cur - base)) over baseline $base)"; fail=1
          elif [ "$cur" -lt "$base" ]; then echo "  ✨ $name: $cur (-$((base - cur)) under baseline $base — lock it!)"; win=1
          else echo "  ✅ $name: $cur (== baseline)"; fi ;;
        down_bad)
          if [ "$cur" -lt "$base" ]; then echo "  ❌ $name: $cur ($((base - cur)) under baseline $base)"; fail=1
          elif [ "$cur" -gt "$base" ]; then echo "  ✨ $name: $cur (+$((cur - base)) over baseline $base — lock it!)"; win=1
          else echo "  ✅ $name: $cur (== baseline)"; fi ;;
      esac
    }

    echo "Ratchet check:"
    check_one "tsc_errors"  "$tsc"   "$base_tsc"   "up_bad"
    check_one "test_count"  "$tests" "$base_tests" "down_bad"
    check_one "todo_count"  "$todos" "$base_todos" "up_bad"
    [ "$win" = 1 ] && { echo; echo "Some metrics improved — lock the win:"; echo "  bash scripts/check-ratchet.sh lock"; }
    exit "$fail"
    ;;
  *)
    echo "Usage: $0 [check|init|lock]" >&2; exit 2
    ;;
esac
